### ISSUE TITLE
 transactions of a previous year 

### ISSUE THREAD

**Issue by ashwin666** [MicrosoftDocs/DynamicsAX2012-technet#198]
I believe transactions of a previous year also cannot be changed if the "opening transactions" General Ledger periodic job is run part of the financial year close process correct ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51537835-14ee-ae4e-aa32-d455ca483282
* Version Independent ID: 46151d4f-e34c-7635-de70-331d17f934cc
* Content: [Reverse a transaction](https://docs.microsoft.com/en-us/dynamicsax-2012/appuser-itpro/reverse-a-transaction)
* Content Source: [dynamicsax2012-technet/reverse-a-transaction.md](https://github.com/microsoftdocs/DynamicsAX2012-technet/blob/live/dynamicsax2012-technet/reverse-a-transaction.md)
* Product: **dynamicsax-2012**
* GitHub Login: @Khairunj

**Comment by roschlom** [comment]
Thank you for the question! Your understanding of what the topic is saying is correct. If you have run the ‘Opening transactions’ (which is the previous name for the GL year-end close), there are some transactions that cannot be reversed, but that’s not the case for all of them. 

Another thing to consider is whether the periods in that year are on hold or permanently closed. If the transactions are permanently closed, it will prevent any transactions from posting, rather than just reverse transactions.

If you haven’t done so already, you might also consider posting your question on the Dynamics 365 community blog, to allow other AX 2012 users to share their experiences and advice. 

Thanks again for reaching out!

**Comment by roschlom** [comment]
I meant for the "Community blog" to be a link: here's the URL to that blog: https://community.dynamics.com/ 

Have a great day!

**Comment by roschlom** [comment]
Ack!! Thank you for closing this. You asked me to do that the other day and I obviously I didn’t remember to do it. : (

Thanks for closing it and for your patience!
